"""Project constants."""

from __future__ import annotations

ALLOWED_JOB_ROLES = (
    "데이터 분석가",
    "데이터 사이언티스트",
    "인공지능 리서처",
    "인공지능 엔지니어",
)

COMPANY_TIERS = (
    "대기업",
    "스타트업",
    "중견/중소",
    "공공·연구기관",
    "외국계 한국법인",
    "지역기업",
)

DISPLAY_FIELDS = (
    "회사명_표시",
    "소스명_표시",
    "공고제목_표시",
    "경력수준_표시",
    "경력근거_표시",
    "채용트랙_표시",
    "채용트랙근거_표시",
    "직무초점_표시",
    "직무초점근거_표시",
    "구분요약_표시",
    "직무명_표시",
    "주요업무_표시",
    "자격요건_표시",
    "우대사항_표시",
    "핵심기술_표시",
)

ANALYSIS_FIELDS = (
    "주요업무_분석용",
    "자격요건_분석용",
    "우대사항_분석용",
    "핵심기술_분석용",
    "상세본문_분석용",
)

IMPORT_COMPANY_COLUMNS = (
    "company_name",
    "company_tier",
    "official_domain",
    "company_name_en",
    "region",
    "aliases",
    "discovery_method",
    "candidate_seed_type",
    "candidate_seed_url",
    "candidate_seed_title",
    "candidate_seed_reason",
)

IMPORT_SOURCE_COLUMNS = (
    "company_name",
    "company_tier",
    "source_name",
    "source_url",
    "source_type",
    "official_domain",
    "is_official_hint",
    "structure_hint",
    "discovery_method",
)

COMPANY_CANDIDATE_COLUMNS = (
    "company_name",
    "company_tier",
    "official_domain",
    "company_name_en",
    "region",
    "aliases",
    "discovery_method",
    "candidate_seed_type",
    "candidate_seed_url",
    "candidate_seed_title",
    "candidate_seed_reason",
    "officiality_score",
    "source_seed_count",
    "verified_source_count",
    "active_job_count",
    "role_analyst_signal",
    "role_ds_signal",
    "role_researcher_signal",
    "role_ai_engineer_signal",
    "role_fit_score",
    "hiring_signal_score",
    "evidence_count",
    "primary_evidence_type",
    "primary_evidence_url",
    "primary_evidence_text",
    "company_bucket",
    "reject_reason",
    "last_verified_at",
)

COMPANY_EVIDENCE_COLUMNS = (
    "company_name",
    "company_tier",
    "evidence_type",
    "evidence_url",
    "evidence_text",
    "role_analyst_signal",
    "role_ds_signal",
    "role_researcher_signal",
    "role_ai_engineer_signal",
    "evidence_strength",
    "captured_at",
)

COMPANY_SEED_SOURCE_COLUMNS = (
    "source_name",
    "source_type",
    "discovered_source_type",
    "source_url",
    "request_url",
    "local_path",
    "source_title",
    "company_tier",
    "candidate_seed_type",
    "candidate_seed_reason",
    "table_index",
    "header_row",
    "company_name_column",
    "official_domain_column",
    "company_name_en_column",
    "region_column",
    "aliases_column",
    "filter_text_columns",
    "include_keywords",
    "exclude_keywords",
    "allowed_domains",
    "discovery_include_keywords",
    "discovery_exclude_keywords",
    "max_discovered_sources",
    "first_seen_at",
    "last_seen_at",
)

RUN_COLUMNS = (
    "run_id",
    "command",
    "status",
    "started_at",
    "finished_at",
    "summary_json",
)

ERROR_COLUMNS = (
    "run_id",
    "command",
    "logged_at",
    "error_type",
    "error_message",
)

SOURCE_REGISTRY_COLUMNS = (
    "company_name",
    "company_tier",
    "source_name",
    "source_url",
    "source_type",
    "source_bucket",
    "source_domain",
    "official_domain",
    "official_domain_confidence",
    "source_quality_score",
    "is_official_hint",
    "structure_hint",
    "discovery_method",
    "verification_status",
    "failure_count",
    "last_success_at",
    "last_active_job_count",
    "quarantine_reason",
    "is_quarantined",
)

JOB_COLUMNS = (
    "job_key",
    "change_hash",
    "first_seen_at",
    "last_seen_at",
    "is_active",
    "missing_count",
    "snapshot_date",
    "run_id",
    "source_url",
    "source_bucket",
    "source_name",
    "company_name",
    "company_tier",
    "job_title_raw",
    "experience_level_raw",
    "job_role",
    "job_url",
    "record_status",
    *ANALYSIS_FIELDS,
    *DISPLAY_FIELDS,
)

RAW_DETAIL_COLUMNS = (
    "run_id",
    "snapshot_date",
    "job_key",
    "source_url",
    "company_name",
    "job_title_raw",
    "raw_payload_json",
)

APPROVED_SOURCE_TYPES = {
    "official_careers",
    "json_api",
    "jsonld",
    "rss",
    "sitemap",
    "greenhouse",
    "lever",
    "greetinghr",
    "recruiter",
    "workable",
    "smartrecruiters",
    "jobvite",
    "ashby",
    "bamboohr",
    "teamtailor",
}

SUPPORTED_SOURCE_TYPES = APPROVED_SOURCE_TYPES | {"html_page"}

ATS_SOURCE_TYPES = {
    "greenhouse",
    "lever",
    "greetinghr",
    "recruiter",
    "workable",
    "smartrecruiters",
    "jobvite",
    "ashby",
    "bamboohr",
    "teamtailor",
}

ASSET_TOKENS = {
    "logo",
    "image",
    "converted",
    "webp",
    "svg",
    "png",
    "jpg",
    "jpeg",
    "favicon",
    "icon",
    "banner",
    "asset",
    "thumbnail",
    "placeholder",
    "full",
}

BLOCKED_LISTING_TOKENS = {
    "채용공고",
    "채용 목록",
    "공고 목록",
    "목록 페이지",
    "공지사항",
    "문서",
    "보고서",
    "상세 페이지",
    "리스트",
    "목록",
    "이미지 설명",
    "이미지",
    "썸네일",
    "alt text",
}

BLOCKED_SOURCE_DOMAINS = {
    "jobkorea.co.kr",
    "www.jobkorea.co.kr",
    "saramin.co.kr",
    "www.saramin.co.kr",
    "wanted.co.kr",
    "www.wanted.co.kr",
    "catch.co.kr",
    "www.catch.co.kr",
    "incruit.com",
    "www.incruit.com",
    "peoplenjob.com",
    "www.peoplenjob.com",
}

COMMON_KOREAN_SURNAMES = {
    "김",
    "이",
    "박",
    "최",
    "정",
    "강",
    "조",
    "윤",
    "장",
    "임",
    "한",
    "오",
    "서",
    "신",
    "권",
    "황",
    "안",
    "송",
    "류",
    "홍",
}

ROLE_KEYWORDS = {
    "데이터 분석가": (
        "데이터 분석가",
        "데이터분석",
        "data analyst",
        "data analytics",
        "analytics analyst",
        "분석가",
    ),
    "데이터 사이언티스트": (
        "데이터 사이언티스트",
        "데이터 사이언스",
        "데이터사이언스",
        "data scientist",
        "applied scientist",
        "data science",
        "응용 과학자",
        "머신러닝 사이언티스트",
    ),
    "인공지능 리서처": (
        "인공지능 리서처",
        "ai researcher",
        "ml researcher",
        "research scientist",
        "research engineer",
        "머신러닝 리서처",
        "리서처",
    ),
    "인공지능 엔지니어": (
        "인공지능 엔지니어",
        "ai 엔지니어",
        "ai 개발자",
        "ai개발자",
        "ai engineer",
        "ai agent engineer",
        "ai 서비스 개발",
        "ai서비스개발",
        "applied ai engineer",
        "ml engineer",
        "machine learning engineer",
        "딥러닝 엔지니어",
        "머신러닝 엔지니어",
    ),
}

KOREAN_HEADER_MAP = {
    "job_key": "공고키",
    "change_hash": "변경해시",
    "first_seen_at": "최초발견시각",
    "last_seen_at": "최종발견시각",
    "is_active": "활성여부",
    "missing_count": "미발견횟수",
    "snapshot_date": "스냅샷일자",
    "run_id": "실행ID",
    "source_url": "소스URL",
    "source_bucket": "소스버킷",
    "source_name": "소스명",
    "company_name": "회사명",
    "company_tier": "기업층",
    "job_title_raw": "공고제목_raw",
    "experience_level_raw": "경력수준_raw",
    "job_role": "분류직무",
    "job_url": "공고URL",
    "record_status": "레코드상태",
    "회사명_표시": "회사명_표시",
    "소스명_표시": "소스명_표시",
    "공고제목_표시": "공고제목_표시",
    "경력수준_표시": "경력수준_표시",
    "경력근거_표시": "경력근거_표시",
    "채용트랙_표시": "채용트랙_표시",
    "채용트랙근거_표시": "채용트랙근거_표시",
    "직무초점_표시": "직무초점_표시",
    "직무초점근거_표시": "직무초점근거_표시",
    "구분요약_표시": "구분요약_표시",
    "직무명_표시": "직무명_표시",
    "주요업무_표시": "주요업무_표시",
    "자격요건_표시": "자격요건_표시",
    "우대사항_표시": "우대사항_표시",
    "핵심기술_표시": "핵심기술_표시",
    "주요업무_분석용": "주요업무_분석용",
    "자격요건_분석용": "자격요건_분석용",
    "우대사항_분석용": "우대사항_분석용",
    "핵심기술_분석용": "핵심기술_분석용",
    "상세본문_분석용": "상세본문_분석용",
    "source_type": "소스유형",
    "source_domain": "소스도메인",
    "official_domain": "공식도메인",
    "company_name_en": "회사명_영문",
    "region": "지역",
    "aliases": "별칭",
    "candidate_seed_type": "후보시드유형",
    "candidate_seed_url": "후보시드URL",
    "candidate_seed_title": "후보시드제목",
    "candidate_seed_reason": "후보시드사유",
    "officiality_score": "공식성점수",
    "source_seed_count": "소스시드수",
    "verified_source_count": "검증성공소스수",
    "active_job_count": "활성공고수",
    "role_analyst_signal": "데이터분석가신호수",
    "role_ds_signal": "데이터사이언티스트신호수",
    "role_researcher_signal": "인공지능리서처신호수",
    "role_ai_engineer_signal": "인공지능엔지니어신호수",
    "role_fit_score": "직무적합점수",
    "hiring_signal_score": "채용신호점수",
    "evidence_count": "근거수",
    "primary_evidence_type": "대표근거유형",
    "primary_evidence_url": "대표근거URL",
    "primary_evidence_text": "대표근거내용",
    "company_bucket": "기업버킷",
    "reject_reason": "제외사유",
    "last_verified_at": "마지막검증시각",
    "evidence_type": "근거유형",
    "evidence_url": "근거URL",
    "evidence_text": "근거내용",
    "evidence_strength": "근거강도",
    "captured_at": "근거수집시각",
    "official_domain_confidence": "공식도메인신뢰도",
    "source_quality_score": "소스품질점수",
    "verification_status": "검증상태",
    "failure_count": "실패횟수",
    "last_success_at": "마지막성공시각",
    "last_active_job_count": "마지막활성공고수",
    "quarantine_reason": "격리사유",
    "is_quarantined": "격리여부",
    "is_official_hint": "공식힌트여부",
    "structure_hint": "구조힌트",
    "discovery_method": "발견방식",
    "summary_json": "요약JSON",
    "status": "상태",
    "command": "명령",
    "started_at": "시작시각",
    "finished_at": "종료시각",
    "logged_at": "기록시각",
    "error_type": "오류유형",
    "error_message": "오류메시지",
    "raw_payload_json": "raw_payload_json",
}

SHEET_TAB_NAMES = (
    "기업선정 탭",
    "기업근거 탭",
    "staging 탭",
    "master 탭",
    "raw/detail 탭",
    "runs 탭",
    "source_registry 탭",
    "errors 탭",
)
